module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'users',
    CATEGORY_COLLECTION:'category',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'orders',
    OFFER_COLLECCTION:'offers',
    COUPON_COLLECTION:'coupons'
}